apiVersion: v1
kind: Deployment
metadata:
  name: hackathon-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hackathon-api
  template:
    metadata:
      labels:
        app: hackathon-api
    spec:
      containers:
      - name: nlp-app
        image: gcr.io/cagip-hackathon-eq11-inno0/myapp:v1
        ports:
        - containerPort: 5000