steps:
  - name: 'gcr.io/cloud-builders/docker'  
    entrypoint: /bin/bash
    args: [ 'docker', 'buildx', 'build', '--no-cache', '--push', '--platform', 'linux/amd64,linux/arm64', '-t', '"${_DOCKER_REPO}/${_IMAGE}:${_TAG}"', '-f', 'Dockerfile', '.' ]
images:
  - 'europe-west1-docker.pkg.dev/cagip-hackathon-eq11-inn0-28/${_REPOSITORY}/${_IMAGE}'
