steps:
  - name: 'docker'  
    entrypoint: docker
    args: ['build','--build-arg','TARGETOS=${_TARGETOS}','--build-arg','TARGETARCH=${_TARGETARCH}','-t', '${_DOCKER_REPO}/${_IMAGE}:${_TAG}', '-f', 'Dockerfile', '.' ]
  - name: 'docker'
    args: ['push', 'royavenn/toto:tagname']

