steps:
  - name: 'docker'  
    entrypoint: docker
    args: ['build','--build-arg','TARGETOS=${_TARGETOS}','--build-arg','TARGETARCH=${_TARGETARCH}','-t', '${_DOCKER_REPO}/${_IMAGE}:${_TAG}', '-f', 'Dockerfile', '.' ]
  - name: 'docker'
    args: ['push', '${_DOCKER_REPO}/${_IMAGE}:${_TAG}']

# images:
#   - 'europe-west1-docker.pkg.dev/cagip-hackathon-eq11-inn0-28/${_REPOSITORY}/${_IMAGE}'
