apiVersion: v1
kind: Namespace
metadata:
  name: hackathon-api2
---
 apiVersion: v1
 kind: ServiceAccount
 metadata:
   name: hackathon-api2-user
   namespace: hackathon-api2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-api2-deployment
  namespace: hackathon-api2
  labels:
    app: hackathon-api2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hackathon-api2
  template:
    metadata:
      labels:
        app: hackathon-api2
    spec:
      serviceAccountName: hackathon-api2-user
      containers:
        - name: hackathon-api2
          image: europe-west1-docker.pkg.dev/cagip-hackathon-eq11-inno0-28/repo-11/hackathon-api:dev
          imagePullPolicy: Always
          env:
            - name: MONGOURI
              value: mongodb://10.28.1.7:27017/donation?retryWrites=true&w=majority
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
            requests:
              memory: 500Mi


---
apiVersion: v1
kind: Service
metadata:
  name: hackathon-api2-svc
  namespace: hackathon-api2
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: hackathon-api2
spec:
    selector:
      app: hackathon-api2
    type: LoadBalancer
    ports:
      # the port that this service should serve on
      - port: 80
        protocol: TCP
        targetPort: 80
